"""empty message

Revision ID: 37cab33633c7
Revises: 7130fce393b4
Create Date: 2024-02-23 15:33:34.577038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37cab33633c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'categories',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('category_code', sa.String(length=20), nullable=False, unique=True),
        sa.Column('index', sa.String(length=20), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    op.create_table(
        'cities',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('city_code', sa.String(length=20), nullable=False, unique=True),
        sa.Column('index', sa.String(length=20), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    op.create_table(
        'events',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('event_code', sa.String(length=20), nullable=False, unique=True, index=True),
        sa.Column('date_start', sa.Date, nullable=True),
        sa.Column('date_end', sa.Date, nullable=True),
        sa.Column('city_code', sa.String(length=20), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('namekz', sa.String(length=128), nullable=True),
        sa.Column('nameen', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    op.create_table(
        'users',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('email', sa.String(length=150), nullable=True, unique=True),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.Column('workplace', sa.String(length=128), nullable=True),
        sa.Column('iin', sa.String(length=12), nullable=False, unique=True),
        sa.Column('phone_number', sa.String(length=20), nullable=True),
        sa.Column('is_accreditator', sa.Boolean, nullable=False, default=False),
        sa.Column('admin', sa.Boolean, nullable=False, default=False),
        sa.Column('last_signed_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('login_count', sa.Integer, nullable=False, default=0),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('namekz', sa.String(length=128), nullable=True),
        sa.Column('nameen', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    op.create_table(
        'users_events',
        sa.Column('user_id', sa.String(length=36), sa.ForeignKey('users.id'), primary_key=True),
        sa.Column('event_id', sa.String(length=36), sa.ForeignKey('events.id'), primary_key=True)
    )
    
    op.create_table(
        'document_types',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('doc_code', sa.String(length=20), nullable=False, unique=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('namekz', sa.String(length=128), nullable=True),
        sa.Column('nameen', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    
    op.create_table(
        'sexes',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('sex_code', sa.String(length=20), nullable=False, unique=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('namekz', sa.String(length=128), nullable=True),
        sa.Column('nameen', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )

    # Create table for Country
    op.create_table(
        'countries',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('country_code', sa.String(length=20), nullable=False, unique=True),
        sa.Column('cis_flag', sa.Boolean, nullable=False, default=False),
        sa.Column('country_iso', sa.String(length=20), nullable=True),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('namekz', sa.String(length=128), nullable=True),
        sa.Column('nameen', sa.String(length=128), nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )

    # Create table for Attendee
    op.create_table(
        'attendees',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('surname', sa.String(length=128), nullable=False),
        sa.Column('firstname', sa.String(length=128), nullable=False),
        sa.Column('patronymic', sa.String(length=128), nullable=True),
        sa.Column('birth_date', sa.Date, nullable=True),
        sa.Column('post', sa.String(length=1024), nullable=True),
        sa.Column('doc_series', sa.String(length=128), nullable=True),
        sa.Column('iin', sa.String(length=12), nullable=False, index=True),
        sa.Column('doc_number', sa.String(length=20), nullable=True),
        sa.Column('doc_begin_date', sa.Date, nullable=True),
        sa.Column('doc_end_date', sa.Date, nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )

    # Create table for Request
    op.create_table(
        'requests',
        sa.Column('id', sa.String(length=36), primary_key=True, index=True),
        sa.Column('name', sa.String(length=128), nullable=False, index=True),
        sa.Column('event_id', sa.String(), sa.ForeignKey('events.id'), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('date_created', sa.DateTime, nullable=False, default=sa.func.now()),
        sa.Column('created_by_id', sa.String(), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('registration_time', sa.DateTime, nullable=True),
        sa.Column('created_at', sa.DateTime, nullable=False, server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime, nullable=False, server_default=sa.func.now(), onupdate=sa.func.now())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    op.drop_table('cities')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('users_events')
    op.drop_table('document_types')
    op.drop_table('requests')
    op.drop_table('attendees')
    op.drop_table('countries')
    op.drop_table('sexes')

    # ### end Alembic commands ###
