from .attendee import attendee_service
from .category import category_service
from .city import city_service
from .country import country_service
from .document_type import document_service
from .event import event_service
from .request import request_service
from .sex import sex_service
from .user import user_service
from .auth import auth_service
